//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorRunner_Databse_First
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class Person
    {
        public Person()
        {
            this.RunnerSponsor = new ObservableCollection<RunnerSponsor>();
            this.RunnerSponsor1 = new HashSet<RunnerSponsor>();
        }
    
        public int PeronId { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string strasse { get; set; }
        public string ort { get; set; }
        public string plz { get; set; }
    
        public virtual ObservableCollection<RunnerSponsor> RunnerSponsor { get; set; }
        public virtual ICollection<RunnerSponsor> RunnerSponsor1 { get; set; }
    }
}
