//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorRunner_Databse_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnerSponsor
    {
        public int RunnerId { get; set; }
        public int SponsorId { get; set; }
        public int Betrag { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
